version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: germesplus
      MYSQL_USER: server
      MYSQL_PASSWORD: server
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - network

  image-storage:
    image: teflondervish/image-storage
    container_name: image-storage
    ports:
      - "8090:8090"
    volumes:
      - image-data:/storage
    environment:
      - FILE_STORAGE=/storage
      - URL=image-storage
    networks:
      - network

  germes-plus:
    image: teflondervish/germes-plus
    container_name: germes-plus
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/germesplus
      SPRING_DATASOURCE_USERNAME: server
      SPRING_DATASOURCE_PASSWORD: server
    ports:
      - "8080:8080"
    networks:
      - network


volumes:
  mysql-data:
  image-data:

networks:
  network:
    driver: bridge