#version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mysql
      - germes-plus
      - germes-plus-manager
      - germes-plus-fabric
      - phpmyadmin
    networks:
      - network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: germesplus
      MYSQL_USER: server
      MYSQL_PASSWORD: server
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8083:80"
    networks:
      - network


  image-storage:
    image: teflondervish/image-storage:latest
    container_name: image-storage
    ports:
      - "8090:8090"
    volumes:
      - image-data:/storage
    environment:
      - FILE_STORAGE=/storage
      - URL=hermes-plus.ru
    networks:
      - network

  germes-plus:
    image: teflondervish/germes-plus:latest
    container_name: germes-plus
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/germesplus
      SPRING_DATASOURCE_USERNAME: server
      SPRING_DATASOURCE_PASSWORD: server
      IMAGE_STORAGE: hermes-plus.ru:8090
    ports:
      - "8080:8080"
    networks:
      - network

  germes-plus-manager:
    image: teflondervish/germes-plus-manager:latest
    container_name: germes-plus-manager
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/germesplus
      SPRING_DATASOURCE_USERNAME: server_manager
      SPRING_DATASOURCE_PASSWORD: server_manager
      IMAGE_STORAGE: hermes-plus.ru:8090
    ports:
      - "8081:8081"
    networks:
      - network


  germes-plus-fabric:
    image: teflondervish/germes-plus-fabric
    container_name: germes-plus-fabric
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/germesplus
      SPRING_DATASOURCE_USERNAME: server_fabric
      SPRING_DATASOURCE_PASSWORD: server_fabric
      IMAGE_STORAGE: hermes-plus.ru:8090
    ports:
      - "8082:8082"
    networks:
      - network

volumes:
  mysql-data:
  image-data:

networks:
  network:
    driver: bridge